gabrielgz92/Celebrent

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml

add devise gem

---

app/models/user.rb
config/initializers/devise.rb
config/routes.rb
db/migrate/20190527052250_devise_create_users.rb
test/models/user_test.rb

Hey guys; added user model. Remember to `db:migrate`

Added model for user

---

app/models/celebrity.rb
db/migrate/20190527061414_create_celebrities.rb
db/schema.rb
test/models/celebrity_test.rb

guys added celeb model, run `db:migrate`
still needs validation

add celeb model

---

app/models/booking.rb
db/migrate/20190527062754_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

added the booking model db:migrate

created a booking model

---

app/models/user.rb
db/migrate/20190527065604_add_fields_to_user.rb
db/schema.rb

Added the missing field for the user model (was created by devise Gem)
remember db:migrate!

Add user missing fields

---

app/models/user.rb

this are the validations for the new fields created, please look them responsibly

added validations for user

---

app/models/celebrity.rb
app/models/user.rb

Added relation in `user` and `celebrity` model

relation_between_celeb_user

---

app/models/celebrity.rb

changed validations

---

app/models/booking.rb

changed validation missing `,`

fix validation booking

---

app/controllers/users_controller.rb
test/controllers/users_controller_test.rb

added `new` and `create` to users model

added create functionality to users controller

---

app/controllers/users_controller.rb
app/uploaders/photo_uploader.rb
app/views/users/_form.html.erb
test/controllers/users_controller_test.rb

added a form view to update user info, may need to check the photo upload because im not 100% sure it's correct

Edit user info

---

app/models/booking.rb
db/seeds.rb

added seed to all booking, user and celebrity models, also corrected ……misspeling in bookings validations. Added numericality integer to duration for bookings.
Remember to run `rails db:seed`
With love, GGZ

Seed to all models. Also corrected validations

---

app/models/celebrity.rb
app/views/celebrities/index.html.erb
app/views/celebrities/show.html.erb

Celebshowview

---

app/views/celebrities/index.html.erb

added `full_name` method in Celebrity model

adjust index cards

---

app/controllers/users_controller.rb
app/views/users/_form.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20190527065604_add_fields_to_user.rb
db/schema.rb

will need to rollback and run another migration

completed basic user profile with edit function

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/views/celebrities/_banner.html.erb
app/views/celebrities/_carousal.html.erb
app/views/celebrities/index.html.erb

banner for index

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/config/_fonts.scss
app/uploaders/photo_uploader.rb

add two gems

---

app/assets/stylesheets/components/_avatar.scss
app/views/celebrities/_banner.html.erb
app/views/shared/_navbar.html.erb
app/views/users/_form.html.erb

changed a little for navbar to show `avatar`

changed nav settings

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_cards.scss
app/controllers/celebrities_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/models/celebrity.rb
app/views/celebrities/show.html.erb
app/views/shared/_navbar.html.erb
config/initializers/geocoder.rb
db/migrate/20190529013315_add_coordinates_to_celebrities.rb
db/migrate/20190529014524_add_location_to_celebrities.rb
db/schema.rb
db/seeds.rb
package.json
yarn.lock

added map to user show

---

Gemfile.lock
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/celebrities/_footer.html.erb
app/views/celebrities/landing.html.erb
db/schema.rb

added footer

---

Gemfile.lock
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/celebrities/_footer.html.erb
app/views/celebrities/landing.html.erb
app/views/shared/_navbar.html.erb
db/schema.rb

Searchform

---

app/models/celebrity.rb
app/models/celebrity_tag.rb
app/models/tag.rb
db/migrate/20190530000826_create_tags.rb
db/migrate/20190530001349_create_celebrity_tags.rb
db/schema.rb
test/models/celebrity_tag_test.rb
test/models/tag_test.rb

added Tag and CelebrityTag models, with their validations and created…one instance. Remember to DB:MIGRATE!!!

Tag and CelebrityTag Models. REMEMBER TO DB:MIGRATE

---

app/assets/stylesheets/components/_cards.scss
app/controllers/bookings_controller.rb
app/views/bookings/_update.html.erb
app/views/bookings/index.html.erb
config/routes.rb

Booking cancellation is now done with an alert
Booking update remains on the booking index page (added alert to confirm changes made)
Restyled booking index cards to accommodate all booking details

updated booking cancellation and restyled the booking index page

---

app/controllers/celebrities_controller.rb
app/controllers/celebrity_tags_controller.rb
app/models/celebrity.rb
app/models/celebrity_tag.rb
app/models/tag.rb
app/views/celebrities/show.html.erb
app/views/celebrity_tags/new.html.erb
config/routes.rb
db/migrate/20190530000826_create_tags.rb
db/migrate/20190530001349_create_celebrity_tags.rb
db/schema.rb
test/models/celebrity_tag_test.rb
test/models/tag_test.rb

Added tag controller and views, now It's possible to select a Tag from the list. I'll be working on JavaScript to make it possible to create new ones.

Added tag controller and views

---

Gemfile
Gemfile.lock
app/javascript/components/init_select2.js
app/javascript/packs/application.js
app/views/celebrity_tags/new.html.erb
app/views/layouts/application.html.erb
db/seeds.rb
package.json
yarn.lock

Now the seeding file is commented, the only part working is the seeding for tags

Tag seeding -----REMEMBER TO SEED and BUNDLE INSTALL for faker

---

db/migrate/20190530050735_add_date_to_bookings.rb
db/schema.rb
db/seeds.rb

added booking date to booking model
RUN db:seed and db:migrate

added booking date to booking model and seededdb with data
